name: Ejecutar pruebas Selenium testNG

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'  # Todos los días a las 2:00 AM UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
          sudo mkdir -p /opt/google/chrome
          [ "$(readlink -f /opt/google/chrome/google-chrome)" != "/usr/bin/google-chrome" ] && sudo ln -sf /usr/bin/google-chrome /opt/google/chrome/google-chrome || echo "Symlink already correct"

      - name: Set DISPLAY variable
        run: echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run tests with Maven using testng.xml
        run: mvn test -DsuiteXmlFile=testng.xml

      - name: Install Allure CLI manually
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.34.1/allure-2.34.1.tgz
          tar -zxvf allure-2.34.1.tgz
          sudo mv allure-2.34.1 /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Generate Allure Report
        run: allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Deploy Allure Report to GitHub Pages
        if: success()
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git clone --branch=gh-pages https://x-access-token:${TOKEN}@github.com/${{ github.repository }} gh-pages
          rm -rf gh-pages/*
          cp -r allure-report/* gh-pages/
          cd gh-pages
          touch .nojekyll
          git add .
          git commit -m "Deploy Allure report"
          git push origin gh-pages